package funktionsplot;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

import javax.swing.JPanel;

public class GraphPanel extends JPanel implements MouseMotionListener, MouseListener, MouseWheelListener {
	/**
	 * autogenerated version id
	 */
	private static final long serialVersionUID = -7250288945960637817L;
	
	private Point mousePressPos = new Point(0,0);	
	private Boundaries boundaries;  
	private List<Color> plotcolors = new ArrayList<Color>();
	private List<Funktion> funktionen = new ArrayList<Funktion>();
	private List<int[]> plots = new ArrayList<int[]>();
	
	//Konstruktor
	public GraphPanel() {
		this.setBackground(Color.WHITE);
		this.addMouseMotionListener(this);
		this.addMouseListener(this);
		this.addMouseWheelListener(this);
		setBoundaries(-30,30,100,-100);		
	}
	
	//getter&setter:
	
	public void addFunction(Funktion f) {
		funktionen.add(f);
		autoPlot(f);
		this.repaint();
	}

	public void setBoundaries(double left, double right, double top, double bottom) {
		boundaries = new Boundaries(left, right, top, bottom);
		plots.clear();
		plotcolors.clear();
		for(Funktion f : funktionen) {
			plot(f);
		}		
		this.repaint();
	}
	
	public Boundaries getBoundaries() {
		return this.boundaries;
	}
	
	//reset everything
	public void reset() {
		funktionen.clear();
		plotcolors.clear();
		plots.clear();
		repaint();
	}
	
	//Umrechnung Funktionswerte->Pixel
	private Point koordinatesToPixel(double x, double y) {
		return new Point(xToPixel(x),yToPixel(y));
	}
	
	///Umrechnung x-Wert->Pixel-x-Wert
	private int xToPixel(double x) {
		return (int)((x-boundaries.left)*(getWidth()/(boundaries.right-boundaries.left)));
	}
	
	//umrechnung y-Wert->Pixel-y-Wert
	private int yToPixel(double y) {
		return (int)(getHeight()-(y-boundaries.bottom)*(getHeight()/(boundaries.top-boundaries.bottom)));
	}
	
	//passt vor dem plotten die y-Achsenskalierung den minima und maxima der im Intervall an
	public void autoPlot(Funktion f) {
		TreeMap<Double, Double> wertetabelle = f.berechneWertetabelle(boundaries.left, boundaries.right, getWidth());
		Double max = f.maximumIn(wertetabelle);
		Double min = f.minimumIn(wertetabelle);
		if(min==max) {
			min-=2;
			max+=2;
		}
		System.out.println(min);
		if(min.isNaN()) {
			System.out.println("min ist infinite");
			min = (double) -10;
		}
		if(max.isNaN()) {
			max = (double) 10;
		}

		double minplot = min - (max-min)/5;
		double maxplot = max + (max-min)/5;
		setBoundaries(boundaries.left, boundaries.right, maxplot, minplot);
	}
	
	//Berechnung der Pixelwerte einer Funkntion
	private void plot(Funktion f) {		
		TreeMap<Double, Double> wertetabelle = f.berechneWertetabelle(boundaries.left, boundaries.right, getWidth());
		
		//zum Debugging von der Funktion Nullstellen
		f.nullstellen(boundaries.left, boundaries.right, getWidth());
		//
		f.Extremstellen(boundaries.left, boundaries.right, getWidth());
		
		int x = 0;
		int[] y = new int[getWidth()];
		for (Double value : wertetabelle.values()) {
			y[x] = yToPixel(value);

			x++;
		}
		plots.add(y);
		plotcolors.add(f.plotColor);
	}
	
	public void zeigeAbleitung(Color color) {
		System.out.println("zeigeAbleitung()");
		if (!funktionen.isEmpty()) {

			Funktion f = funktionen.get(0).ableitung();
			f.plotColor = color;
			f.print();
			
			addFunction(f);
		}
	}


	//Alles zeichnen -> aufruf über this.repaint();
	@Override
    protected void paintComponent(Graphics g) {
		int w = this.getWidth();
		int h = this.getHeight();
		
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
           
        // erzeugt schwarzen Rand um das Panel
        g2.setColor(Color.BLACK);
        g2.drawRect(0, 0, w-1, h-1);
        
        // erzeugt Achsen
        g2.drawLine(xToPixel(0), 0,  xToPixel(0), h);        
        g2.drawLine(0, yToPixel(0), w, yToPixel(0));
         
        //Markierungen x-Achse
        double schrittweite = 1;
        double intervallbreite = boundaries.right-boundaries.left;
        if(intervallbreite >= 20) {
        	while(intervallbreite/schrittweite>20) {
        		schrittweite*=10;
        	}
        }
        else {
        	while((intervallbreite/schrittweite)<2) {
        		schrittweite/=10;
        	}
        }
    	if (intervallbreite/schrittweite<5) {
    		schrittweite/=2;
    	}		
        Double xStrich=(double) 0;
        while(xStrich<boundaries.right) {
        	xStrich+=schrittweite;
        	g2.drawLine(xToPixel(xStrich), yToPixel(0)-3, xToPixel(xStrich), yToPixel(0)+3 );
        	g2.drawString(xStrich.toString(), xToPixel(xStrich)- 4  , yToPixel(0)+ 15 );
        }
        xStrich=(double) 0;
        while(xStrich>boundaries.left) {
        	xStrich-=schrittweite;
        	g2.drawLine(xToPixel(xStrich) , yToPixel(0)-3 , xToPixel(xStrich) , yToPixel(0)+3 );
        	g2.drawString(xStrich.toString(), xToPixel(xStrich)- 4  , yToPixel(0)+ 15 );
        }
        
        //Markierungen Y-Achse
        schrittweite = 1;
        double intervallhoehe = boundaries.top-boundaries.bottom;
        if(intervallhoehe >= 20) {
        	while(intervallhoehe/schrittweite>20) {
        		schrittweite*=10;
        	}
        }
        else {
        	while((intervallhoehe/schrittweite)<2) {
        		schrittweite/=10;
        	}
        }
    	if (intervallhoehe/schrittweite<5) {
    		schrittweite/=2;
    	}		
        Double yStrich=(double) 0;
        while(yStrich<boundaries.top) {
        	yStrich+=schrittweite;
        	g2.drawLine(xToPixel(0)+3, yToPixel(yStrich),xToPixel(0)-3,yToPixel(yStrich));
        	g2.drawString(yStrich.toString(), xToPixel(0)+15, yToPixel(yStrich)-4);
        }
        yStrich=(double) 0;
        while(yStrich>boundaries.bottom) {
        	yStrich-=schrittweite;
        	g2.drawLine(xToPixel(0)+3, yToPixel(yStrich),xToPixel(0)-3,yToPixel(yStrich));
        	g2.drawString(yStrich.toString(), xToPixel(0)+15, yToPixel(yStrich)-4);
        }
        
        //zeichne Funktionen ein
        for(int i = 0; i < plots.size(); i++) {
        	g2.setColor(plotcolors.get(i));
        	int[] plot=plots.get(i);
        	for(int x = 0; x < getWidth(); x++) {
        		if(x==0)
        		{
            		g.drawRect(x, plot[x], 1, 1);
        		}
        		else {
        			g.drawLine(x, plot[x-1], x, plot[x]);
        		}
        	}
        }
        
        // Achsenbezeichnung
        // Bezeichnungen weiÃŸ hinterlegen
        g2.setColor(Color.WHITE);
        g2.fillRect(w - 30, yToPixel(0) + 10, 20, 20);
        g2.fillRect(xToPixel(0) - 20, 10, 20, 20);
        
        g2.setColor(Color.DARK_GRAY);
        // Font Ã¤ndern (fÃ¼rs erste defaultFont zwischenspeichern)
        Font defaultFont = g2.getFont();
        g2.setFont(new Font("Bold", Font.BOLD, 18));
        
        
        g2.drawString("x", w - 30, yToPixel(0) + 20);
        g2.drawString("y", xToPixel(0) - 20, 20);
	}

	//MouselListener-Methoden:
	
	@Override
	public void mouseDragged(MouseEvent e) {
		//probeweise boundaries beim draggen updaten
		//aufräumen falls es so bleiben soll
		Point Offset = new Point(0,0);
		Offset.x = -(mousePressPos.x-e.getX());
		Offset.y = (e.getY()-mousePressPos.y);
		
		double xShift = -(Offset.x*(boundaries.right-boundaries.left))/this.getWidth();
		double yShift = (Offset.y*(boundaries.top-boundaries.bottom))/this.getHeight();
		
		setBoundaries(boundaries.left+xShift, boundaries.right+xShift, boundaries.top+yShift, boundaries.bottom+yShift);
		mousePressPos.x=e.getX();
		mousePressPos.y=e.getY();
		Offset.x=0;
		Offset.y=0;
		this.repaint();
	}

	@Override
	public void mouseMoved(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseClicked(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		mousePressPos = new Point(e.getX(), e.getY());;
	}

	@Override
	public void mouseReleased(MouseEvent e) {
				
	}
	@Override
	public void mouseWheelMoved(MouseWheelEvent e) {
		double zoomFactor = 1.5;
		double width = boundaries.right-boundaries.left;
		double height = boundaries.top-boundaries.bottom;
		double xDirection = (double)e.getX()/getWidth();
		double yDirection = (double)e.getY()/getHeight();
		if(e.getWheelRotation()==-1) {			
			setBoundaries(boundaries.left-((width*zoomFactor-width)*(xDirection)), boundaries.right+((width*zoomFactor-width)*(1-xDirection)),
					boundaries.top+((height*zoomFactor-height)*(yDirection)), boundaries.bottom-((height*zoomFactor-height)*(1-yDirection)));
		}
		else {
			setBoundaries(boundaries.left-(width/zoomFactor-width)*(xDirection), boundaries.right+(width/zoomFactor-width)*(1-xDirection),
					boundaries.top+(height/zoomFactor-height)*(yDirection), boundaries.bottom-(height/zoomFactor-height)*(1-yDirection));
		}
	}


}
